'use client'

import { useEffect, useState } from 'react'
import { Loader2, Lock, Award, ExternalLink } from 'lucide-react'

// Preview proxies can stall a lone response until a concurrent request nudges
// the pipe — fire one unblocking ping at 500ms (same strategy as the main app).
const ping = (() => { let last = 0; return () => { const now = Date.now(); if (now - last < 300) return; last = now; fetch('/api/root', { cache: 'no-store', signal: AbortSignal.timeout(3000) }).catch(() => {}) } })()
const fetchJson = (url) => {
  const p = fetch(url, { cache: 'no-store', credentials: 'same-origin' })
  let settled = false
  p.then(() => { settled = true }, () => { settled = true })
  setTimeout(() => { if (!settled) ping() }, 500)
  return p
}

// Public, read-only "proof of skill" page — opt-in items only.
export default function RecruiterPage() {
  const [state, setState] = useState({ loading: true, data: null, error: null })
  useEffect(() => {
    const q = new URLSearchParams(window.location.search)
    fetchJson(`/api/recruiter/public?slug=${encodeURIComponent(q.get('slug') || '')}&passcode=${encodeURIComponent(q.get('passcode') || '')}`)
      .then(async (r) => {
        if (!r.ok) { const d = await r.json().catch(() => ({})); throw new Error(d.error || 'Not found') }
        return r.json()
      })
      .then((data) => setState({ loading: false, data, error: null }))
      .catch((e) => setState({ loading: false, data: null, error: e.message }))
  }, [])

  return (
    <div className="min-h-screen grid-bg text-white p-6 md:p-12 flex flex-col items-center" style={{ background: '#09090B' }}>
      <div className="w-full max-w-3xl">
        {state.loading && (
          <div className="text-center py-24"><Loader2 className="h-8 w-8 animate-spin text-blue-400 mx-auto mb-3" /><p className="text-sm text-gray-400 font-code">Verifying link…</p></div>
        )}
        {state.error && !state.loading && (
          <div className="text-center py-24">
            <Lock className="h-8 w-8 mx-auto mb-3 text-amber-400" />
            <h1 className="font-bold text-xl mb-1">{state.error === 'Passcode required' ? 'This page is passcode-protected' : 'Link not found'}</h1>
            <p className="text-sm text-gray-400">Ask the owner for the correct URL and passcode.</p>
          </div>
        )}
        {state.data && !state.loading && (
          <div>
            <div className="mb-10">
              <div className="inline-flex items-center gap-2 mb-4 px-3 py-1 rounded-full border border-white/10 text-xs text-gray-400 font-code"><Award className="h-3.5 w-3.5 text-amber-400" /> VERIFIED PROOF OF WORK</div>
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight">{state.data.name}</h1>
              <p className="text-blue-400 mt-2 font-medium">{state.data.headline}</p>
              <p className="text-sm text-gray-400 mt-3 leading-relaxed">Selected, verified work from a live content-automation system. Every item below was hand-picked and passed a human approval gate before it reached the internet.</p>
            </div>
            <div className="space-y-4">
              {state.data.items.map((i) => (
                <div key={i.id} className="rounded-xl p-5 border border-white/10" style={{ background: '#18181B' }}>
                  <div className="flex items-start gap-3">
                    <div className="text-xs font-code text-amber-400 pt-0.5 shrink-0">{i.category}</div>
                    <div className="min-w-0">
                      <div className="font-semibold">{i.title}</div>
                      {i.reason && <div className="text-sm text-gray-400 mt-1">{i.reason}</div>}
                      {i.url && <a href={i.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs text-blue-400 mt-2 hover:underline">View content <ExternalLink className="h-3 w-3" /></a>}
                    </div>
                  </div>
                </div>
              ))}
              {!state.data.items.length && <p className="text-sm text-gray-400 py-10 text-center">No proof items selected yet.</p>}
            </div>
            <div className="mt-12 text-center text-xs text-gray-500">Generated by NEXUS — an AI content command center operating with a human-in-the-loop approval gate.</div>
          </div>
        )}
      </div>
    </div>
  )
}
